# Default environment
default:

  # Default log level (documented in LogSettings class)
  runtime_log_level: info

  # Default log filename prefix (documented in LogSettings class)
  runtime_log_filename_prefix: main

  # Packages to load (documented in ContextSettings class)
  runtime_context_packages:
    - cl.runtime
    - cl.convince
    - cl.tradeentry
    - cl.hackathon
    - stubs.cl.runtime
    - stubs.cl.convince
    - stubs.cl.tradeentry
    - stubs.cl.hackathon

  # Database settings (documented in ContextSettings class)
  runtime_context_db_class: cl.runtime.db.sql.sqlite_db.SqliteDb

  # REST API hostname and port (documented in ApiSettings class)
  runtime_api_hostname: localhost
  runtime_api_port: 7008

  # Preload directories to include (documented in PreloadSettings class)
  runtime_preload_dirs:
    - cl

  # Documented in LlmSettings class
  convince_llm_locale: en-US
  convince_llm_full: gpt-4o
  convince_llm_mini: gpt-4o-mini

# Test environment
test:

  # Test log filename prefix (documented in LogSettings class)
  runtime_log_filename_prefix: tests
